/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academicwarfare;

/**
 *
 * @author onur.elbirlik
 */
public class MainMenu extends javax.swing.JPanel {

    /**
     * Creates new form JPanel
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        options = new javax.swing.JButton();
        highScores = new javax.swing.JButton();
        exitGame = new javax.swing.JButton();
        mainTitle = new javax.swing.JLabel();
        mainMenuTitle = new javax.swing.JLabel();
        tutorial = new javax.swing.JButton();
        loadGame = new javax.swing.JButton();
        newGame = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 102));

        options.setForeground(new java.awt.Color(255, 102, 0));
        options.setText("Options");
        options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsActionPerformed(evt);
            }
        });

        highScores.setForeground(new java.awt.Color(255, 102, 0));
        highScores.setText("HighScores");
        highScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highScoresActionPerformed(evt);
            }
        });

        exitGame.setForeground(new java.awt.Color(255, 102, 0));
        exitGame.setText("Exit Game");
        exitGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitGameActionPerformed(evt);
            }
        });

        mainTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mainTitle.setForeground(new java.awt.Color(255, 102, 0));
        mainTitle.setText("Academic Warfare");

        mainMenuTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mainMenuTitle.setForeground(new java.awt.Color(255, 102, 0));
        mainMenuTitle.setText("Main Menu");

        tutorial.setForeground(new java.awt.Color(255, 102, 0));
        tutorial.setText("Tutorial");
        tutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorialActionPerformed(evt);
            }
        });

        loadGame.setForeground(new java.awt.Color(255, 102, 0));
        loadGame.setText("Load Game");
        loadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadGameActionPerformed(evt);
            }
        });

        newGame.setForeground(new java.awt.Color(255, 102, 0));
        newGame.setText("New Game");
        newGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mainTitle)
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loadGame)
                            .addComponent(newGame, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainMenuTitle)
                            .addComponent(tutorial, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(options, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(highScores)
                            .addComponent(exitGame, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(215, 215, 215))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(mainTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainMenuTitle)
                .addGap(42, 42, 42)
                .addComponent(newGame)
                .addGap(18, 18, 18)
                .addComponent(loadGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tutorial)
                .addGap(18, 18, 18)
                .addComponent(options)
                .addGap(15, 15, 15)
                .addComponent(highScores)
                .addGap(18, 18, 18)
                .addComponent(exitGame)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void optionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsActionPerformed
       new Options().setVisible(true);
    }//GEN-LAST:event_optionsActionPerformed

    private void highScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highScoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_highScoresActionPerformed

    private void exitGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitGameActionPerformed

    private void tutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tutorialActionPerformed

    private void loadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadGameActionPerformed

    private void newGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newGameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitGame;
    private javax.swing.JButton highScores;
    private javax.swing.JButton loadGame;
    private javax.swing.JLabel mainMenuTitle;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JButton newGame;
    private javax.swing.JButton options;
    private javax.swing.JButton tutorial;
    // End of variables declaration//GEN-END:variables
}
